---
galaxy_info:
  author: fe80
  description: Install and configure nomad server
  license: Apache-2.0

  min_ansible_version: 2.10

  platforms:
  - name: Ubuntu
    versions:
      - jammy

  galaxy_tags:
    - system
    - common

dependencies: []
